### ISSUE TITLE
增加教學引導

### ISSUE THREAD

**Issue by noracami** [side-project-at-SPT/split-front#2]

**Comment by noracami** [comment]
https://tailwindcss.com/docs/hover-focus-and-other-states#highlighted-text

可以改一下反白的顏色？
淺藍色背景反白不太明顯

**Comment by tom00502** [comment]
> https://tailwindcss.com/docs/hover-focus-and-other-states#highlighted-text
> 
> 可以改一下反白的顏色？ 淺藍色背景反白不太明顯

done
